function containsAny(text, keywords) {
  return keywords.some((keyword) => text.includes(keyword));
}

export async function analyzeFeedbackWithMockAi(feedback) {
  const text = feedback.feedback_text.toLowerCase();

  const isSafety = containsAny(text, [
    "unsafe",
    "injury",
    "smoke",
    "fire",
    "slip",
    "fell",
    "leak",
    "mold",
    "electrical",
    "security"
  ]);
  const isService = containsAny(text, ["rude", "ignored", "staff", "check-in", "check out", "service"]);
  const isFacilities = containsAny(text, ["room", "bathroom", "air conditioning", "elevator", "wifi", "dirty"]);
  const isOperations = containsAny(text, ["delay", "billing", "reservation", "late", "housekeeping", "queue"]);
  const isPositive = containsAny(text, ["great", "excellent", "friendly", "wonderful", "amazing", "thank you"]);

  let category = "other";
  if (isSafety) {
    category = "safety";
  } else if (isService) {
    category = "service";
  } else if (isFacilities) {
    category = "facilities";
  } else if (isOperations) {
    category = "operations";
  }

  const sentiment = isPositive && !containsAny(text, ["not", "never", "poor", "bad"]) ? "positive" : text.includes("okay") ? "neutral" : "negative";

  const safety_risk = isSafety ? 8.5 : containsAny(text, ["broken", "flood", "alarm"]) ? 6.5 : 2.5;
  const guest_impact = containsAny(text, ["couldn't", "unable", "ruined", "terrible", "waited", "dirty"]) ? 8 : isPositive ? 2 : 5.5;
  const brand_reputation_risk = containsAny(text, ["never again", "complaint", "review", "social media", "refund"]) ? 8 : 4.5;

  let recommended_action = "Log the feedback and monitor for repeat patterns.";
  if (category === "safety") {
    recommended_action = "Dispatch the duty manager immediately and secure the affected area.";
  } else if (category === "service") {
    recommended_action = "Contact the guest, coach the staff involved, and document the service recovery.";
  } else if (category === "facilities") {
    recommended_action = "Create a maintenance ticket and confirm repair timing with operations.";
  } else if (category === "operations") {
    recommended_action = "Review the workflow bottleneck and assign an owner for same-day resolution.";
  }

  return {
    category,
    sentiment,
    safety_risk,
    guest_impact,
    brand_reputation_risk,
    recommended_action,
    rationale: "Generated by deterministic local mock rules for testing."
  };
}
